"""
Organize data folder to integrate new generation with existing structure
"""

import shutil
from pathlib import Path
import json


def main():
    print("🔧 Organizing data structure...\n")
    
    base_dir = Path("data")
    
    # 1. Create new subdirectories
    print("1. Creating new directories...")
    new_dirs = [
        ("generated/code_files", "Additional randomly generated MLIR programs"),
        ("generated/train", "Training augmentation data"),
        ("generated/eval", "Evaluation augmentation data"),
        ("neural_nets/resnet", "ResNet family converted to MLIR"),
        ("neural_nets/bert", "BERT/Transformer models"),
        ("neural_nets/custom", "Custom neural networks"),
        ("data/benchmarks/single_ops", "Single operation benchmarks"),
        ("data/benchmarks/neural_nets", "Full neural network benchmarks"),
    ]
    
    for dir_path, description in new_dirs:
        full_path = base_dir / dir_path
        full_path.mkdir(parents=True, exist_ok=True)
        
        # Create README
        readme = full_path / "README.md"
        if not readme.exists():
            with open(readme, 'w') as f:
                f.write(f"# {dir_path.split('/')[-1].title()}\n\n")
                f.write(f"{description}\n\n")
                f.write(f"Generated by: organize_data.py\n")
        
        print(f"  ✓ {dir_path}")
    
    # 2. Move test files if they exist
    print("\n2. Moving test files...")
    moves = [
        ("test_generation", "generated/test"),
        ("test_nn_conversion", "neural_nets/test"),
    ]
    
    for src, dst in moves:
        src_path = base_dir / src
        dst_path = base_dir / dst
        
        if src_path.exists():
            dst_path.mkdir(parents=True, exist_ok=True)
            for f in src_path.glob("*.mlir"):
                shutil.move(str(f), str(dst_path / f.name))
            if not any(src_path.iterdir()):
                src_path.rmdir()
            print(f"  ✓ {src} → {dst}")
        else:
            print(f"  - {src} (not found, skipping)")
    
    # 3. Create .gitignore for generated data
    print("\n3. Creating .gitignore files...")
    gitignore_content = """# Generated MLIR files (can be regenerated)
*.mlir

# Keep README and JSON files
!README.md
!*.json
"""
    
    for subdir in ["generated", "neural_nets", "benchmarks"]:
        gitignore_path = base_dir / subdir / ".gitignore"
        with open(gitignore_path, 'w') as f:
            f.write(gitignore_content)
        print(f"  ✓ {subdir}/.gitignore")
    
    # 4. Print final structure
    print("\n" + "="*60)
    print("✅ Data structure organized!\n")
    print_structure()
    
    # 5. Statistics
    print("\n" + "="*60)
    print("📊 Statistics:\n")
    
    all_dir = base_dir / "all" / "code_files"
    test_dir = base_dir / "test" / "code_files"
    
    existing_all = len(list(all_dir.glob("*.mlir"))) if all_dir.exists() else 0
    existing_test = len(list(test_dir.glob("*.mlir"))) if test_dir.exists() else 0
    
    print(f"  Existing data/all/code_files:    {existing_all} files")
    print(f"  Existing data/test/code_files:   {existing_test} files")
    print(f"  New structure ready for:         500+ augmentation files")
    print(f"  Neural networks supported:       ResNet, BERT, Custom")
    
    print("\n" + "="*60)
    print("\n🚀 Next steps:\n")
    print("  1. Generate augmentation data:")
    print("     python scripts/augment_dataset.py")
    print("\n  2. Convert neural networks:")
    print("     python data_generation/nn_to_mlir.py")
    print("\n  3. Train with augmented data:")
    print("     CONFIG_FILE_PATH=config/config.json python bin/train.py")


def print_structure():
    """Print the organized directory structure"""
    structure = """Final Structure:
    
data/
├── all/                          ✓ EXISTING: Primary training data
│   ├── code_files/              (400+ MLIR files)
│   └── execution_times_*.json
│
├── test/                        ✓ EXISTING: Test/validation data  
│   ├── code_files/
│   └── execution_times_*.json
│
├── generated/                   ✓ NEW: Augmentation data
│   ├── code_files/             (Additional random MLIR)
│   ├── train/                  (Training augmentation)
│   ├── eval/                   (Eval augmentation)
│   ├── test/                   (Test files from integration)
│   └── .gitignore
│
├── neural_nets/                 ✓ NEW: Converted networks
│   ├── resnet/                 (ResNet-18, 34, 50)
│   ├── bert/                   (BERT, DistilBERT)
│   ├── custom/                 (User models)
│   ├── test/                   (Test files from integration)
│   └── .gitignore
│
└── data/benchmarks/                  ✓ NEW: Evaluation suites
    ├── single_ops/             (matmul, conv2d, etc.)
    ├── neural_nets/            (End-to-end networks)
    └── .gitignore

Usage:
  • data/all/       → Training (existing workflow)
  • data/generated/ → Augment training data
  • data/neural_nets/ → Test on real networks
  • data/benchmarks/ → Evaluation & comparison
"""
    print(structure)


if __name__ == "__main__":
    main()
