#!/bin/bash
# Quick Reference: DistilBERT Model in MLIR-RL

echo "DistilBERT Model - Quick Commands"
echo "=================================="
echo ""

echo "1. SETUP"
echo "--------"
echo "Install dependencies:"
echo "  pip install transformers>=4.30.0"
echo ""
echo "Or install all:"
echo "  pip install -r requirements.txt"
echo ""

echo "2. VALIDATE INSTALLATION"
echo "------------------------"
echo "Test tokenizer and data preprocessing:"
echo "  python test_distilbert_data.py"
echo ""
echo "Test core DistilBERT:"
echo "  python test_distilbert_simple.py"
echo ""
echo "Test full integration:"
echo "  python test_distilbert.py"
echo ""

echo "3. TRAINING"
echo "-----------"
echo "Train with DistilBERT (test config):"
echo "  CONFIG_FILE_PATH=config/config_distilbert.json python bin/train.py"
echo ""
echo "Train with LSTM (default):"
echo "  CONFIG_FILE_PATH=config/config.json python bin/train.py"
echo ""

echo "4. EVALUATION"
echo "-------------"
echo "Evaluate DistilBERT model:"
echo "  CONFIG_FILE_PATH=config/config_distilbert.json python bin/evaluate.py"
echo ""

echo "5. SWITCHING MODELS"
echo "-------------------"
echo "Edit any config file and change:"
echo '  "model_type": "lstm"      # Use LSTM (default, fast)'
echo '  "model_type": "distilbert" # Use DistilBERT (slower, potentially better)'
echo ""

echo "6. FILES CHANGED"
echo "----------------"
echo "Core implementation:"
echo "  - rl_autoschedular/model.py (added DistilBertEmbedding)"
echo "  - utils/config.py (added model_type field)"
echo "  - config/config.json (added model_type parameter)"
echo ""
echo "New files:"
echo "  - config/config_distilbert.json"
echo "  - test_distilbert.py"
echo "  - test_distilbert_simple.py"
echo "  - docs/DISTILBERT_MODEL.md"
echo ""

echo "7. HYPERPARAMETERS"
echo "------------------"
echo "Recommended for DistilBERT:"
echo "  lr: 0.0001 (vs 0.001 for LSTM)"
echo "  ppo_batch_size: 8-16 (vs 32 for LSTM)"
echo "  value_batch_size: 8-16 (vs 32 for LSTM)"
echo ""

echo "8. DOCUMENTATION"
echo "----------------"
echo "Full documentation:"
echo "  docs/DISTILBERT_MODEL.md"
echo ""
echo "Implementation summary:"
echo "  DISTILBERT_IMPLEMENTATION.md"
echo ""

echo "=================================="
echo "For questions, check the documentation or test scripts"
